#!/usr/bin/env python

import os
import base64
import subprocess
import time
import click
import pydisplay

TITLE=''
WIN='null'

@click.command(context_settings={'help_option_names':['-h','--help']})
@click.argument('images', nargs=-1, type=click.Path(exists=True), required=True)
@click.option('--win', '-w', default='')
@click.option('--title', '-t', default='')
def disp(images, win, title):
    # TODO tiling option
    for img_fname in images:
        print img_fname
        base, ext = os.path.splitext(img_fname)
        ext = ext.replace('.', '')
        ext = ext.replace('jpeg', 'jpg')
        valid_ext = set(['png','gif','bmp','webp','pdf','jpg'])
        if not ext.lower() in valid_ext:
            raise Exception('unrecognized image format: {}'.format(ext))
        with open(img_fname, 'rb') as f:
            encoded = pydisplay.b64_encode(f.read(), ext)
        pydisplay.send(command='image', id=win, title=title, src=encoded)


if __name__ == '__main__':
    disp()
